// Auto-generated by scripts/generate-photo-data.mjs — do not edit by hand.
// Re-run "npm run generate:photos" after adding or removing an image.
const photoManifest: Record<string, string> = {
  "ban-haw-mosque": "/images/places/ban-haw-mosque.jpg",
  "bhubing-palace": "/images/places/bhubing-palace.jpg",
  "chiang-mai-city-arts-cultural-centre": "/images/places/chiang-mai-city-arts-cultural-centre.jpg",
  "doi-inthanon": "/images/places/doi-inthanon.jpg",
  "kad-suan-kaew": "/images/places/kad-suan-kaew.jpg",
  "mae-sa-waterfall": "/images/places/mae-sa-waterfall.jpg",
  "nong-buak-hard-park": "/images/places/nong-buak-hard-park.jpg",
  "san-kamphaeng-hot-springs": "/images/places/san-kamphaeng-hot-springs.jpg",
  "tha-phae-gate": "/images/places/tha-phae-gate.jpg",
  "three-kings-monument": "/images/places/three-kings-monument.jpg",
  "wat-ban-den": "/images/places/wat-ban-den.jpg",
  "wat-buak-khrok-luang": "/images/places/wat-buak-khrok-luang.jpg",
  "wat-buppharam": "/images/places/wat-buppharam.jpg",
  "wat-chedi-luang": "/images/places/wat-chedi-luang.jpg",
  "wat-chet-yot": "/images/places/wat-chet-yot.jpg",
  "wat-chiang-man": "/images/places/wat-chiang-man.jpg",
  "wat-chiang-yuen": "/images/places/wat-chiang-yuen.jpg",
  "wat-duang-di": "/images/places/wat-duang-di.jpg",
  "wat-inthrawat-ton-kwen": "/images/places/wat-inthrawat-ton-kwen.jpg",
  "wat-jed-lin": "/images/places/wat-jed-lin.jpg",
  "wat-ket-karam": "/images/places/wat-ket-karam.jpg",
  "wat-lok-molee": "/images/places/wat-lok-molee.jpg",
  "wat-mahawan": "/images/places/wat-mahawan.jpg",
  "wat-pan-whaen": "/images/places/wat-pan-whaen.jpg",
  "wat-pha-lat": "/images/places/wat-pha-lat.jpg",
  "wat-phan-on": "/images/places/wat-phan-on.jpg",
  "wat-phan-tao": "/images/places/wat-phan-tao.jpg",
  "wat-phra-non-khon-muang": "/images/places/wat-phra-non-khon-muang.jpg",
  "wat-phra-singh": "/images/places/wat-phra-singh.jpg",
  "wat-phra-that-doi-kham": "/images/places/wat-phra-that-doi-kham.jpg",
  "wat-phra-that-doi-saket": "/images/places/wat-phra-that-doi-saket.jpg",
  "wat-phra-that-doi-suthep": "/images/places/wat-phra-that-doi-suthep.jpg",
  "wat-phuak-hong": "/images/places/wat-phuak-hong.jpg",
  "wat-saen-fang": "/images/places/wat-saen-fang.jpg",
  "wat-si-koet": "/images/places/wat-si-koet.jpg",
  "wat-sri-suphan": "/images/places/wat-sri-suphan.jpg",
  "wat-umong": "/images/places/wat-umong.jpg",
  "wat-umong-maha-thera-chan": "/images/places/wat-umong-maha-thera-chan.jpg",
  "wiang-tha-kan": "/images/places/wiang-tha-kan.jpg",
  "48-hours-in-nimman": "/images/guides/48-hours-in-nimman.jpg",
  "cafe-hopping-route": "/images/guides/cafe-hopping-route.jpg",
  "temples-of-the-old-city": "/images/guides/temples-of-the-old-city.jpg"
};

export function getPlacePhoto(slug: string): string | undefined {
  return photoManifest[slug];
}

export default photoManifest;
