// Auto-generated by scripts/fetch-place-photos.mjs — do not edit by hand.
// Re-run "npm run fetch:photos" to refresh.
const photoManifest: Record<string, string> = {
  "wat-phra-that-doi-suthep": "/images/places/wat-phra-that-doi-suthep.jpg",
  "wat-chedi-luang": "/images/places/wat-chedi-luang.jpg",
  "wat-phra-singh": "/images/places/wat-phra-singh.jpg",
  "wat-umong": "/images/places/wat-umong.jpg",
  "wat-sri-suphan": "/images/places/wat-sri-suphan.jpg",
  "wat-suan-dok": "/images/places/wat-suan-dok.jpg",
  "doi-inthanon": "/images/places/doi-inthanon.jpg",
  "bua-tong-sticky-waterfall": "/images/places/bua-tong-sticky-waterfall.jpg",
  "chiang-mai-grand-canyon": "/images/places/chiang-mai-grand-canyon.jpg",
  "doi-pui": "/images/places/doi-pui.jpg",
  "mon-cham": "/images/places/mon-cham.jpg",
  "huay-tung-tao": "/images/places/huay-tung-tao.jpg",
  "mae-kampong": "/images/places/mae-kampong.jpg",
  "baan-tawai": "/images/places/baan-tawai.jpg",
  "wua-lai-silver-village": "/images/places/wua-lai-silver-village.jpg",
  "nimmanhaemin": "/images/places/nimmanhaemin.jpg",
  "riverside-ping": "/images/places/riverside-ping.jpg",
  "old-city-coffee-trail": "/images/places/old-city-coffee-trail.jpg",
  "ban-kang-wat": "/images/places/ban-kang-wat.jpg",
  "sunday-walking-street-thapae": "/images/places/sunday-walking-street-thapae.jpg",
  "saturday-walking-street-wualai": "/images/places/saturday-walking-street-wualai.jpg",
  "warorot-market": "/images/places/warorot-market.jpg",
  "night-bazaar": "/images/places/night-bazaar.jpg",
  "thai-cooking-class": "/images/places/thai-cooking-class.jpg",
  "thai-massage-spa": "/images/places/thai-massage-spa.jpg",
  "ethical-elephant-sanctuary": "/images/places/ethical-elephant-sanctuary.jpg",
  "48-hours-in-nimman": "/images/guides/48-hours-in-nimman.jpg",
  "cafe-hopping-route": "/images/guides/cafe-hopping-route.jpg",
  "temples-of-the-old-city": "/images/guides/temples-of-the-old-city.jpg"
};

export function getPlacePhoto(slug: string): string | undefined {
  return photoManifest[slug];
}

export default photoManifest;
