/**
 * Who took each photograph, under what licence, and where the original lives.
 *
 * This is not a courtesy list. Most place photography here comes from
 * Wikimedia Commons under CC BY / CC BY-SA, where naming the author and the
 * licence is a condition of being allowed to use the image at all — so a photo
 * with no entry here must not be displayed.
 *
 * The Commons block below is generated by scripts/generate-photo-data.mjs from
 * the last fetch run — edits there are lost on the next run. Photos from any
 * other source go in MANUAL_CREDITS, which the generator never touches.
 */
export interface PhotoCredit {
  /** Photographer or uploader, as the source records them. */
  artist: string;
  /** Short licence name, e.g. "CC BY-SA 3.0". */
  licence: string;
  /** The image's own page at the source — where the full licence text lives. */
  sourceUrl: string;
  /**
   * The Wikidata entity the photo was attached to, which is what proves it
   * depicts this place. Absent for the few photos that did not come through
   * that pipeline; those carry their evidence in a comment instead.
   */
  entity?: string;
}

/**
 * Photos not sourced from Commons, kept by hand.
 *
 * Each one needs a reason it can be trusted to show the place it is captioned
 * with, written down here, because nothing automatic checked it.
 */
const MANUAL_CREDITS: Record<string, PhotoCredit> = {
  // Wat Umong has no Wikidata entity within 400m, so the fetcher cannot reach
  // it. This is the one survivor of the old Pexels set: its source title is
  // "man posing in historic thai temple tunnel", and the image shows the brick
  // tunnel with a gilded Buddha at the end, which no other temple in Chiang Mai
  // has. Pexels does not require attribution; the photographer is named anyway.
  "wat-umong": {
    artist: "Pete Miller Portraits",
    licence: "Pexels licence",
    sourceUrl: "https://www.pexels.com/photo/man-posing-in-historic-thai-temple-tunnel-35446052/",
  },
};

const photoCredits: Record<string, PhotoCredit> = {
  "ban-haw-mosque": {
    artist: "Iceway12 at en.wikipedia",
    licence: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Baan_Haw_Mosque_4-6-09.jpg",
    entity: "Q4022414",
  },
  "bhubing-palace": {
    artist: "whyyan",
    licence: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bhubing_Palace_(7981858020).jpg",
    entity: "Q4902096",
  },
  "chiang-mai-city-arts-cultural-centre": {
    artist: "Stefan Fussan",
    licence: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chiang_Mai_-_Chiang_Mai_City_Art_and_Cultural_Center_-_0001.jpg",
    entity: "Q18808485",
  },
  "doi-inthanon": {
    artist: "Plenz",
    licence: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:InthanonChedi1.jpg",
    entity: "Q1140075",
  },
  "kad-suan-kaew": {
    artist: "Vano111ru",
    licence: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%E0%B8%AD%E0%B8%B8%E0%B8%97%E0%B8%A2%E0%B8%B2%E0%B8%99%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%84%E0%B9%89%E0%B8%B2%E0%B8%81%E0%B8%B2%E0%B8%94%E0%B8%AA%E0%B8%A7%E0%B8%99%E0%B9%81%E0%B8%81%E0%B9%89%E0%B8%A7.jpg",
    entity: "Q13024177",
  },
  "mae-sa-waterfall": {
    artist: "jon collier from waltham, ma, usa",
    licence: "CC BY-SA 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2014-Thailand-358_(15990792649).jpg",
    entity: "Q111449536",
  },
  "nong-buak-hard-park": {
    artist: "Kawin Jungsakulrujirek",
    licence: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Buak_Hard_Park.jpg",
    entity: "Q16255674",
  },
  "san-kamphaeng-hot-springs": {
    artist: "Taguelmoust",
    licence: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sankamphaeng002.JPG",
    entity: "Q16639025",
  },
  "tha-phae-gate": {
    artist: "Douglas Perkins",
    licence: "CC BY 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Eastern_Gate_of_Chiang_Mai.jpg",
    entity: "Q13016585",
  },
  "three-kings-monument": {
    artist: "Sry85",
    licence: "CC BY 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:3_kings_monument.JPG",
    entity: "Q13017454",
  },
  "wat-ban-den": {
    artist: "FredTC",
    licence: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Wat_Ban_Den,_the_Ubosot_building_and_surrounding_buildings_P_20180109_134854_1_p.jpg",
    entity: "Q99736007",
  },
  "wat-buak-khrok-luang": {
    artist: "Takeaway",
    licence: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Wat_Buak_Krok_Luang_06.jpg",
    entity: "Q16004191",
  },
  "wat-buppharam": {
    artist: "กสิณธร ราชโอรส",
    licence: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:(2022)_%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%9A%E0%B8%B8%E0%B8%9E%E0%B8%9E%E0%B8%B2%E0%B8%A3%E0%B8%B2%E0%B8%A1_%E0%B8%AD.%E0%B9%80%E0%B8%A1%E0%B8%B7%E0%B8%AD%E0%B8%87_%E0%B8%88.%E0%B9%80%E0%B8%8A%E0%B8%B5%E0%B8%A2%E0%B8%87%E0%B9%83%E0%B8%AB%E0%B8%A1%E0%B9%88,Wat_Buppharam,Chiangmai_(6).jpg",
    entity: "Q1167874",
  },
  "wat-chedi-luang": {
    artist: "Vyacheslav Argenberg",
    licence: "CC BY 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Wat_Chedi_Luang,_Buddhist_temple,_Chiang_Mai,_Thailand.jpg",
    entity: "Q1454288",
  },
  "wat-chet-yot": {
    artist: "memorable",
    licence: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%E0%B9%80%E0%B8%88%E0%B8%94%E0%B8%B5%E0%B8%A2%E0%B9%8C%E0%B9%80%E0%B8%88%E0%B9%87%E0%B8%94%E0%B8%A2%E0%B8%AD%E0%B8%94.jpg",
    entity: "Q2552284",
  },
  "wat-chiang-man": {
    artist: "Supanut Arunoprayote",
    licence: "CC BY 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Wat_Chiang_Man_(I).jpg",
    entity: "Q1515582",
  },
  "wat-chiang-yuen": {
    artist: "Chainwit.",
    licence: "CC BY 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chiang_Mai_-_Stupa_of_Wat_Chiang_Yuen_-_%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B8%A1%E0%B8%AB%E0%B8%B2%E0%B8%98%E0%B8%B2%E0%B8%95%E0%B8%B8%E0%B9%80%E0%B8%88%E0%B8%94%E0%B8%B5%E0%B8%A2%E0%B9%8C_%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B9%80%E0%B8%8A%E0%B8%B5%E0%B8%A2%E0%B8%87%E0%B8%A2%E0%B8%B7%E0%B8%99_%E0%B8%88.%E0%B9%80%E0%B8%8A%E0%B8%B5%E0%B8%A2%E0%B8%87%E0%B9%83%E0%B8%AB%E0%B8%A1%E0%B9%88_(2026)_-_IMG_10.jpg",
    entity: "Q1699542",
  },
  "wat-duang-di": {
    artist: "Stefan Fussan",
    licence: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chiang_Mai_-_Wat_Duang_Di_-_0001.jpg",
    entity: "Q18046080",
  },
  "wat-inthrawat-ton-kwen": {
    artist: "Takeaway",
    licence: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Wat_Ton_Kwaen_02.jpg",
    entity: "Q73152458",
  },
  "wat-jed-lin": {
    artist: "Stefan Fussan",
    licence: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chiang_Mai_-_Wat_Chet_Lin_-_0007.jpg",
    entity: "Q16004163",
  },
  "wat-ket-karam": {
    artist: "Vichitsilp",
    licence: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Watket.jpg",
    entity: "Q13020896",
  },
  "wat-lok-molee": {
    artist: "Flying Pharmacist",
    licence: "CC BY 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Wat_lok_molee_-_Vihara.jpg",
    entity: "Q843027",
  },
  "wat-mahawan": {
    artist: "Christophe95",
    licence: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Wat_Mahawan.jpg",
    entity: "Q110313689",
  },
  "wat-pan-whaen": {
    artist: "Takeaway",
    licence: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Wat_phan_waen_chiang_mai.jpg",
    entity: "Q109985214",
  },
  "wat-pha-lat": {
    artist: "Stefan Fussan",
    licence: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chiang_Mai_-_Wat_Pha_Lat_-_0001.jpg",
    entity: "Q20642064",
  },
  "wat-phan-on": {
    artist: "Stefan Fussan",
    licence: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chiang_Mai_-_Wat_Phan_On_-_0017.jpg",
    entity: "Q18702273",
  },
  "wat-phan-tao": {
    artist: "Vichitsilp",
    licence: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%E0%B8%A7%E0%B8%B4%E0%B8%AB%E0%B8%B2%E0%B8%A3%E0%B9%84%E0%B8%A1%E0%B9%89%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%9E%E0%B8%B1%E0%B8%99%E0%B9%80%E0%B8%95%E0%B8%B2.JPG",
    entity: "Q20475796",
  },
  "wat-phra-non-khon-muang": {
    artist: "Thanya1",
    licence: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B8%99%E0%B8%AD%E0%B8%99%E0%B8%82%E0%B8%AD%E0%B8%99%E0%B8%A1%E0%B9%88%E0%B8%A7%E0%B8%871.JPG",
    entity: "Q13020758",
  },
  "wat-phra-singh": {
    artist: "Stefan Fussan",
    licence: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chiang_Mai_-_Wat_Phra_Singh_-_0004.jpg",
    entity: "Q1657130",
  },
  "wat-phra-that-doi-kham": {
    artist: "ManoiCMU",
    licence: "CC BY 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Wat_Phra_That_Doi_Kham_chedi.jpg",
    entity: "Q13020753",
  },
  "wat-phra-that-doi-saket": {
    artist: "lopsura",
    licence: "CC BY 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%E0%B8%9E%E0%B8%A3%E0%B8%B0%E0%B8%98%E0%B8%B2%E0%B8%95%E0%B8%B8%E0%B8%94%E0%B8%AD%E0%B8%A2%E0%B8%AA%E0%B8%B0%E0%B9%80%E0%B8%81%E0%B9%87%E0%B8%94_-_panoramio.jpg",
    entity: "Q43845478",
  },
  "wat-phra-that-doi-suthep": {
    artist: "เทวประภาส มากคล้าย",
    licence: "CC BY 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Phra_That_Doi_Suthep_01.jpg",
    entity: "Q1517698",
  },
  "wat-phuak-hong": {
    artist: "Kokunut555",
    licence: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ancient_stupa_in_Wat_Puag_Hong_,_Chiangmai_,Thailand.jpg",
    entity: "Q20155454",
  },
  "wat-saen-fang": {
    artist: "Chainwit.",
    licence: "CC BY 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chiang_Mai_-_Wat_Saen_Fang_-_%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B9%81%E0%B8%AA%E0%B8%99%E0%B8%9D%E0%B8%B2%E0%B8%87_%E0%B9%80%E0%B8%8A%E0%B8%B5%E0%B8%A2%E0%B8%87%E0%B9%83%E0%B8%AB%E0%B8%A1%E0%B9%88_(2026)_-_IMG_24.jpg",
    entity: "Q28405193",
  },
  "wat-si-koet": {
    artist: "Chainwit.",
    licence: "CC BY 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chiang_Mai_-_Wat_Si_Koet_%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%A8%E0%B8%A3%E0%B8%B5%E0%B9%80%E0%B8%81%E0%B8%B4%E0%B8%94_%E0%B9%80%E0%B8%8A%E0%B8%B5%E0%B8%A2%E0%B8%87%E0%B9%83%E0%B8%AB%E0%B8%A1%E0%B9%88_(2026)_-_IMG_06.jpg",
    entity: "Q20051158",
  },
  "wat-sri-suphan": {
    artist: "Justraveling.com",
    licence: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Silver_Temple_in_Chiang_Mai.jpg",
    entity: "Q59641379",
  },
  "wat-umong-maha-thera-chan": {
    artist: "Stefan Fussan",
    licence: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chiang_Mai_-_Wat_Umong_Maha_Therachan_-_0001.jpg",
    entity: "Q18713202",
  },
  "wiang-tha-kan": {
    artist: "Andromeda Oscar",
    licence: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%E0%B8%A7%E0%B8%B1%E0%B8%94%E0%B8%95%E0%B9%89%E0%B8%99%E0%B8%81%E0%B8%AD%E0%B8%81_%E0%B9%80%E0%B8%A7%E0%B8%B5%E0%B8%A2%E0%B8%87%E0%B8%97%E0%B9%88%E0%B8%B2%E0%B8%81%E0%B8%B2%E0%B8%99.JPG",
    entity: "Q20898012",
  },
};

/** Generated Commons credits plus the hand-kept ones, as one lookup. */
const allCredits: Record<string, PhotoCredit> = { ...photoCredits, ...MANUAL_CREDITS };

export function getPhotoCredit(slug: string): PhotoCredit | undefined {
  return allCredits[slug];
}

/** Every credited photo, for the credits page. */
export function allPhotoCredits(): (PhotoCredit & { slug: string })[] {
  return Object.entries(allCredits)
    .map(([slug, credit]) => ({ slug, ...credit }))
    .sort((a, b) => a.slug.localeCompare(b.slug));
}

export default allCredits;
